#Numpay Tutorial

In [1]:
import numpy as np


**np.int8 expalins that it is 8 bits you can change it to 32 or 64 for large number**

In [2]:
myarr = np.array([[1,3,5,7]],np.int8)

In [3]:
myarr

array([[1, 3, 5, 7]], dtype=int8)

**to access any element of array**

In [4]:
myarr[0,1]

np.int8(3)

**to get the info of the array which tells this array has 1 row and 4 columns**

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int8')

**can change the array**

In [7]:
myarr[0,1]=9

In [8]:
myarr

array([[1, 9, 5, 7]], dtype=int8)

**Array Creation method: Conversion from other Python structures (i.e. lists and tuples)**

In [9]:
listarray= np.array([[1,2,3],[3,5,7],[9,2,11]])

In [10]:
listarray

array([[ 1,  2,  3],
       [ 3,  5,  7],
       [ 9,  2, 11]])

In [11]:
listarray.dtype

dtype('int64')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

**by adding dectionary**

In [14]:
np.array({34,56,76})

array({56, 34, 76}, dtype=object)

**Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)**

In [15]:
zeros= np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(2, 5)

In [19]:
zeros.size

10

In [20]:
rng= np.arange(10)

In [21]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**linspace gives the elemnets in given range like (1,50,10) here it gives 10 elements in the range of 1-50**

In [22]:
lspace= np.linspace(1.50,10)

In [23]:
lspace

array([ 1.5       ,  1.67346939,  1.84693878,  2.02040816,  2.19387755,
        2.36734694,  2.54081633,  2.71428571,  2.8877551 ,  3.06122449,
        3.23469388,  3.40816327,  3.58163265,  3.75510204,  3.92857143,
        4.10204082,  4.2755102 ,  4.44897959,  4.62244898,  4.79591837,
        4.96938776,  5.14285714,  5.31632653,  5.48979592,  5.66326531,
        5.83673469,  6.01020408,  6.18367347,  6.35714286,  6.53061224,
        6.70408163,  6.87755102,  7.05102041,  7.2244898 ,  7.39795918,
        7.57142857,  7.74489796,  7.91836735,  8.09183673,  8.26530612,
        8.43877551,  8.6122449 ,  8.78571429,  8.95918367,  9.13265306,
        9.30612245,  9.47959184,  9.65306122,  9.82653061, 10.        ])

In [24]:
lspace= np.linspace(1,4,4)

In [25]:
lspace

array([1., 2., 3., 4.])

In [26]:
emp= np.empty((2,4))

In [27]:
emp

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
emp_like= np.empty_like(lspace)

In [29]:
emp_like

array([1., 2., 3., 4.])

In [30]:
arr= np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr= arr.ravel()

In [34]:
arr.shape

(99,)

In [35]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [36]:
ar = np.array(x)

In [38]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [39]:
ar.sum(axis=0)

array([12,  8,  9])

**axis0 means column and axis 1 means rows**

In [40]:
ar.sum(axis=1)

array([ 6, 15,  8])

**to transpose an array i.e convert columns into rows**

In [43]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

**flat gives an iterator**

In [44]:
ar.flat

In [45]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


**.ndim gives  number of dimensions of in array**

In [46]:
ar.ndim

2

In [47]:
ar.size

9

In [48]:
ar.nbytes

72